name       : nemo
version    : 5.6.5
release    : 3
source     :
    - https://github.com/linuxmint/nemo/archive/refs/tags/5.6.5.tar.gz : 7e9e6c58222e07c40bc0ebd2c930b599ec781b7678721e01c6a75dfdc995ec94
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.gtk
summary    : File browser for Cinnamon
description: |
    Nemo is the file manager for the Cinnamon desktop environment.
builddeps  :
    - pkgconfig(cinnamon-desktop)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libgnomekbdui) # This should be pulled in by xapp, but it isn't
    - pkgconfig(libgsf-1)
    - pkgconfig(libselinux)
    - pkgconfig(xapp)
rundeps    :
    - cinnamon-translations
setup      : |
    # Rename 'Files' app name to avoid having the same as nautilus
    sed -i '/^\[Desktop Entry/,/^\[Desktop Action/ s/^Name\(.*\)=.*/Name\1=Nemo/' data/nemo.desktop.in

    %meson_configure -Dselinux=true
build      : |
    %ninja_build
install    : |
    %ninja_install
