name       : nemo
version    : 5.8.4
release    : 6
source     :
    - https://github.com/linuxmint/nemo/archive/refs/tags/5.8.4.tar.gz : 07697806a59ef884f39c4654fe3e96b980f7c5ef6658c0531647ece1692bd4a2
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.gtk
summary    : File browser for Cinnamon
description: |
    Nemo is the file manager for the Cinnamon desktop environment.
builddeps  :
    - pkgconfig(cinnamon-desktop)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libexif)
    - pkgconfig(libgnomekbdui) # This should be pulled in by xapp, but it isn't
    - pkgconfig(libgsf-1)
    - pkgconfig(libselinux)
    - pkgconfig(xapp)
rundeps    :
    - cinnamon-translations
setup      : |
    # Rename 'Files' app name to avoid having the same as nautilus
    sed -i '/^\[Desktop Entry/,/^\[Desktop Action/ s/^Name\(.*\)=.*/Name\1=Nemo/' data/nemo.desktop.in

    %meson_configure -Dselinux=true
build      : |
    %ninja_build
install    : |
    %ninja_install
